// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetInstalledPackages():Promise<Array<main.AppPackage>>;

export function GetPackageDetails(arg1:string,arg2:string):Promise<main.PackageDetails>;

export function GetPackageFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function LaunchPackage(arg1:string):Promise<void>;

export function OpenPackageLocation(arg1:string,arg2:string):Promise<void>;

export function UninstallPackage(arg1:string,arg2:string,arg3:string):Promise<void>;
