// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetInstalledPackages() {
  return window['go']['main']['App']['GetInstalledPackages']();
}

export function GetPackageDetails(arg1, arg2) {
  return window['go']['main']['App']['GetPackageDetails'](arg1, arg2);
}

export function GetPackageFiles(arg1, arg2) {
  return window['go']['main']['App']['GetPackageFiles'](arg1, arg2);
}

export function LaunchPackage(arg1) {
  return window['go']['main']['App']['LaunchPackage'](arg1);
}

export function OpenPackageLocation(arg1, arg2) {
  return window['go']['main']['App']['OpenPackageLocation'](arg1, arg2);
}

export function UninstallPackage(arg1, arg2, arg3) {
  return window['go']['main']['App']['UninstallPackage'](arg1, arg2, arg3);
}
